name: loginui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  dropdown_button2: ^2.3.9
  google_fonts: ^6.2.1

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets: 
    - image/pic2.jpg
    - image/pic1.jpg
    - image/fb.png
    - image/gg.png
    - image/profile_pic.png
    - image/pic3.jpg
    - image/pic4.jpg
    - image/vector.png
